import { listagem } from "./ListaCard";

/*Criando uma array ccom para a Lista de Livros */
export const ListaDeLivros: listagem[] = [
  {
    id: 1,
    titulo: "Atlântida",
    autor: "Dario Velozzo",
    ano: 1938,
    lido: false,
  },
  {
    id: 2,
    titulo: "A metamorfose",
    autor: "Franz Kafka",
    ano: 1915,
    lido: true,
  },
  {
    id: 3,
    titulo: "Tudo é Rio",
    autor: "Carla Madeira",
    ano: 2014,
    lido: true,
  },
  {
    id: 4,
    titulo: "O peso do pássaro morto",
    autor: "Aline Bei",
    ano: 2017,
    lido: true,
  },
  {
    id: 5,
    titulo: "Memórias do Subsolo",
    autor: "Fiodor Dostoievski",
    ano: 1864,
    lido: false,
  },
  {
    id: 6,
    titulo: "Olhos d'água",
    autor: "Conceição Evaristo",
    ano: 2014,
    lido: false,
  },
  {
    id: 7,
    titulo: "Capitães da areia",
    autor: "Jorge Amado",
    ano: 1937,
    lido: true,
  },
  { id: 8, titulo: "Fundação", autor: "Isaac Azimov", ano: 1959, lido: false },
  {
    id: 9,
    titulo: "Torto Arado",
    autor: "Itamar Vieira Junior",
    ano: 2019,
    lido: false,
  },
  {
    id: 10,
    titulo: "Volta ao mundo em 80 dias",
    autor: "Júlio Verne",
    ano: 1872,
    lido: false,
  },
  {
    id: 11,
    titulo: "Quarto de despejo",
    autor: "Carolina Maria de Jesus",
    ano: 1960,
    lido: true,
  },
  {
    id: 12,
    titulo: "Um amor feliz",
    autor: "Wislawa Szymborska",
    ano: 2011,
    lido: true,
  },
  {
    id: 13,
    titulo: "Canções de atormentar",
    autor: "Angélica Freitas",
    ano: 2020,
    lido: true,
  },
  {
    id: 14,
    titulo: "Um defeito de cor",
    autor: "Ana Maria Gonçalves",
    ano: 2006,
    lido: false,
  },
  {
    id: 15,
    titulo: "Um útero é do tamanha de um punho",
    autor: "Angélica Freitas",
    ano: 2012,
    lido: true,
  },
  {
    id: 16,
    titulo: "O livro das semelhanças",
    autor: "Ana Martins Marques",
    ano: 2015,
    lido: false,
  },
  {
    id: 17,
    titulo: "Sinuca embaixo d'água",
    autor: "Carol Bensimon",
    ano: 2009,
    lido: false,
  },
];
